### ISSUE TITLE
Use apexcharts

### ISSUE THREAD

**Issue by adiralashiva8** [prashanth-sams/pytest-html-reporter#151]
Apexchart are pretty awesome, they have download chart option, zoom and much more

Reference - https://apexcharts.com/javascript-chart-demos/column-charts/basic/

**Comment by prashanth-sams** [comment]
@adiralashiva8 is it paid version?

**Comment by adiralashiva8** [comment]
Free and open source, will create a pull request with changes in couple of hours

**Comment by prashanth-sams** [comment]
Thank you @adiralashiva8; do you have skype?

**Comment by adiralashiva8** [comment]
Closing this issue. Current charts are pretty good and scope for apex charts usage is not found (current template required changes to use apex which i feel not required)
