### ISSUE TITLE
[Test case] error not shown for the xfail cases

### ISSUE THREAD

**Issue by prashanth-sams** [prashanth-sams/pytest-html-reporter#163]
![image](https://user-images.githubusercontent.com/2948696/94369088-beeca000-00f8-11eb-953f-63742d602a3a.png)

Info: `tests/functional/test_simple.py:10`

**Comment by prashanth-sams** [comment]
![image](https://user-images.githubusercontent.com/2948696/94369127-fc512d80-00f8-11eb-8629-d0c6927f7fc4.png)

**Comment by tarunmudgal** [comment]
Added a fix for this issue
