### ISSUE TITLE
Execution time is coming as 0 all the time in test metrics section, screenshot attached

### ISSUE THREAD

**Issue by testautomasi** [prashanth-sams/pytest-html-reporter#175]
![issue](https://user-images.githubusercontent.com/55787179/100903614-1e49a080-34ec-11eb-8bd2-1ba373fa9d0d.png)

I am using it in api tests but time is always coming as zero even for tests having time>1 seconds.

Also, I would like to have a facility to display time in ms instead of seconds, is this configuration available?

**Comment by prashanth-sams** [comment]
@testautomasi thanks for reporting; lemme take a look

**Comment by stevezmac** [comment]
Hi @prashanth-sams im also having this issue, was it resolved?

**Comment by tbhatt-conga** [comment]
hi @prashanth-sams  - any solution for execution time coming as 0 in testmatrices section?

**Comment by prashanth-sams** [comment]
Fixed! will be available in version `0.2.5`
