### ISSUE TITLE
Customization of report path and screenshot path

### ISSUE THREAD

**Issue by dkjha52** [prashanth-sams/pytest-html-reporter#176]
I would like to set the report path and screenshot path from script (conftest.py). Can you please provide me the sample example.

**Comment by prashanth-sams** [comment]
Use cli cmd `--html-report` for custom folder.
```
pytest tests/functional/ --html-report=./your_custom_report_folder
```

If you use `pytest.ini`, 
```
addopts = -vs -rf --html-report=./report
```

**Note:** don't need to worry about the screenshot path, as it will automatically point to the custom report folder.
