### ISSUE TITLE
Change in the report name dynamically based on the module.  

### ISSUE THREAD

**Issue by priya24it** [prashanth-sams/pytest-html-reporter#192]
we changed the name in html_template.py file... but this is static approach.. I am just looking to do change dynamically

**Comment by nireshs** [comment]
> we changed the name in html_template.py file... but this is static approach.. I am just looking to do change dynamically

@priya24it yes this changes needed. 
@prashanth-sams thanks for all your effort to make this plugin. Really nice to see this detailed and graphical representation of the test report 👍

**Comment by nireshs** [comment]
@prashanth-sams Please review my changes for the HTML report name update from environment variable. Thanks for your support
@priya24it Can you please try this change and let me know your feedback.

**Comment by prashanth-sams** [comment]
@nireshs @priya24it Added this feature in `0.2.7`
Sample Usage:
```
pytest tests/ --html-report=./report/report.html  --title='YOUR CUSTOM TITLE'
```
